"""empty message

Revision ID: 329c4f9a046a
Revises: cf1d860dc0ae
Create Date: 2022-01-22 13:55:52.260037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329c4f9a046a'
down_revision = 'cf1d860dc0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
